name: CI Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify index.html exists
        run: |
          echo "Liste des fichiers racine:"
          ls -la
          if [ -f index.html ]; then
            echo "index.html trouvé ✅"
          else
            echo "index.html manquant ❌"
            exit 1
          fi

      - name: Simple test message
        run: echo "CI Pipeline exécuté avec succès !"
